import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { trpc } from '@/lib/trpc'
import StoryCard from '@/components/storyCard'
import styles from '@/styles/Home.module.scss'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [id, setId] = useState(1); 
  const story = trpc.story.useQuery(id);
  return (
    <>
      <Head>
        <title>Create your own Adventure!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {story.isLoading && <div>Loading...</div>}
          {story.isError && <div>Error: {story.error.message}</div>}
          {story.isSuccess && <StoryCard story={story.data} setId={setId} />}
        </div>
      </main>
    </>
  )
}
